openapi: 3.0.3
info:
  title: Introduction
  contact:
    email: support@scrypt.io
  version: v1
  description: The sCrypt Open API provides endpoints for accessing and managing various aspects of BRC-20 tokens, Ordinals inscriptions, and Runes on BTC. 
  

    It allows developers to retrieve detailed information about specific tokens, holders, and balances, as well as to interact with inscription data and Rune specifics.

  
    The API ensures secure access through JWT bearer authentication.
servers:
  - url: https://open-api.scrypt.io/v1
tags:
  - name: BRC-20
  - name: Inscriptions
  - name: Runes
paths:
  /btc/{network}/brc20/{ticker}/info:
    get:
      tags:
        - BRC-20
      description: Get the infomation of BRC-20 by ticker.
      operationId: Get BRC-20 Ticker Info
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: ticker
          in: path
          description: BRC-20 ticker
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  id: '1'
                  original_tick: ordi
                  tick: ordi
                  max_supply: '21000000000000000000000000'
                  decimals: 18
                  limit_per_mint: '1000000000000000000000'
                  remaining_supply: '0'
                  burned_supply: '0'
                  is_self_mint: false
                  deploy_inscription_id: b61b0172d95e266c18aea0c624db987e971a5d6d4ebc2aaed85da4642d635735i0
                  block_height: 779832
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
  /btc/{network}/brc20/{ticker}/holders:
    get:
      tags:
        - BRC-20
      description: Get the holders of BRC-20 by ticker.
      operationId: Get BRC-20 Holders
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: ticker
          in: path
          description: BRC-20 ticker
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: paging limit
          required: false
          schema:
            type: number
        - name: offset
          in: query
          description: paging offset
          required: false
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  - pkscript: 0014bf1916dc33dbdd65f60d8b1f65eb35e8120835fc
                    wallet: bc1qhuv3dhpnm0wktasd3v0kt6e4aqfqsd0uhfdu7d
                    overall_balance: '8712082383523010000000000'
                    available_balance: '8712082383523010000000000'
                  - pkscript: 002042135392c4b08a5d7194640340976513b2b100a3e4f50d56fbd70099c633b81e
                    wallet: bc1qggf48ykykz996uv5vsp5p9m9zwetzq9run6s64hm6uqfn33nhq0ql9t85q
                    overall_balance: '1681390956909560000000000'
                    available_balance: '6038956909560000000000'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
  /btc/{network}/brc20/{ticker}/addresses/{address}/balances:
    get:
      tags:
        - BRC-20
      description: Get BRC-20 balance by address and ticker.
      operationId: Get Address BRC-20 Balance
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: ticker
          in: path
          description: BRC-20 ticker
          required: true
          schema:
            type: string
        - name: address
          in: path
          description: BTC address
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  overall_balance: '502730000000000000000'
                  available_balance: '0'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
  /btc/{network}/brc20/addresses/{address}/balances:
    get:
      tags:
        - BRC-20
      description: Get BRC-20 balance list by address.
      operationId: Get Address BRC-20 Balance List
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: address
          in: path
          description: BTC address
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: paging limit
          required: false
          schema:
            type: number
        - name: offset
          in: query
          description: paging offset
          required: false
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  - ticker: ordi
                    overall_balance: '502730000000000000000'
                    available_balance: '0'
                  - ticker: maga
                    overall_balance: '10500000000000000000000'
                    available_balance: '0'
                  - ticker: ordg
                    overall_balance: '666000000000000000000'
                    available_balance: '0'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []
  /btc/{network}/inscriptions/{id}:
    get:
      tags:
        - Inscriptions
      description: Get Ordinals inscription info by inscription ID.
      operationId: Get Inscription Info
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: inscription ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  address: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                  charms: []
                  children: []
                  content_length: 57
                  content_type: text/plain;charset=utf-8
                  effective_content_type: text/plain;charset=utf-8
                  fee: 1464
                  height: 844353
                  id: 09f3acc92192536db3a0566da000cf931a9560799f893ab4cd08f6c4f022c549i0
                  next: 1d7dd8c77d19e6caa4f14e1d82e1085e1c49c33fd00ba4a54fa287df19c21b7fi0
                  number: 70932816
                  parents: []
                  previous: c2edab35d99d18cf1fd96d66096e3477e10c5fb06e5e3df1fe8c0cfec3f85c17i2
                  rune: null
                  sat: null
                  satpoint: 09f3acc92192536db3a0566da000cf931a9560799f893ab4cd08f6c4f022c549:0:0
                  timestamp: 1716240503
                  value: 330
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Inscription ID not found
      security:
        - bearerAuth: []
  /btc/{network}/inscriptions/{id}/content:
    get:
      tags:
        - Inscriptions
      description: Get Ordinals inscription content info by inscription ID.
      operationId: Get Inscription Content
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: inscription ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              example:
                p: brc-20
                op: transfer
                tick: MAGA
                amt: '3000'
            text/html:
              example:
            application/xhtml+xml:
              example:
            application/xml;q=0.9:
              example:
            image/avif:
              example:
            image/webp:
              example:
            image/apng:
              example:
            image/*:
              example:
            application/signed-exchange;v=b3;q=0.7:
              example:
            application/json:
              example:
            application/octet-stream:
              example:
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Inscription ID not found
      security:
        - bearerAuth: []
  /btc/{network}/runes/{nameOrId}/info:
    get:
      tags:
        - Runes
      description: Get rune info by rune name or ID.
      operationId: Get Runes Info
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: nameOrId
          in: path
          description: Rune name or ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  - rune_id: '840106:129'
                    burned: '0'
                    divisibility: 8
                    etching: 535c886ea53e4724bee9e54a3aac9d8aa4feda38a2d4c37597fc0ee524a02c0a
                    terms_amount: '2009010300000000'
                    terms_cap: '0'
                    terms_height_l: null
                    terms_height_h: null
                    terms_offset_l: null
                    terms_offset_h: null
                    mints: '0'
                    premine: '2009010300000000'
                    rune_name: SATOSHIRUNETITAN
                    spacers: '1088'
                    symbol: null
                    timestamp: '2024-04-20T19:57:59.000Z'
                    turbo: false
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Rune name of ID not found
      security:
        - bearerAuth: []
  /btc/{network}/runes/{nameOrId}/holders:
    get:
      tags:
        - Runes
      description: Get rune holders by Rune name or ID.
      operationId: Get Runes Holders
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: nameOrId
          in: path
          description: Rune name or ID
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: paging limit
          required: false
          schema:
            type: number
        - name: offset
          in: query
          description: paging offset
          required: false
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  - pkscript: 512094ce6b24219eec616476994848636e1d57551ae031e348a1a0d8a4dcfbd2db2c
                    wallet_addr: bc1pjn8xkfppnmkxzerkn9yyscmwr4t42xhqx8353gdqmzjde77jmvkq2drg8p
                    rune_id: '840106:129'
                    total_balance: '14640700000000'
                    rune_name: SATOSHIRUNETITAN
                  - pkscript: 5120844a80e9c09978d4a47184d615820e791977dd179071c5f8d375e59ccaa9b0d7
                    wallet_addr: bc1ps39gp6wqn9udffr3sntptqsw0yvh0hghjpcut7xnwhjeej4fkrtsl03jmy
                    rune_id: '840106:129'
                    total_balance: '13915000000000'
                    rune_name: SATOSHIRUNETITAN
                  - pkscript: 512005df61448f8e0cc04a8dccef62207e7f91091b12013127d9fccd7365d09934bc
                    wallet_addr: bc1pqh0kz3y03cxvqj5denhkygr707gsjxcjqycj0k0ue4ekt5yexj7qh0e659
                    rune_id: '840106:129'
                    total_balance: '10000000000000'
                    rune_name: SATOSHIRUNETITAN
                  - pkscript: 5120011b49e3dd553c684e471b12e6eea0d017b9e0c69a0638cad6b1174603037560
                    wallet_addr: bc1pqyd5nc7a257xsnj8rvfwdm4q6qtmncxxngrr3jkkkyt5vqcrw4sq67fk7g
                    rune_id: '840106:129'
                    total_balance: '10000000000000'
                    rune_name: SATOSHIRUNETITAN
                  - pkscript: 512003f067cd6aee8a1340621e4e3cbeacb9c1ce72583b44a46f142ebeadfe54c078
                    wallet_addr: bc1pq0cx0nt2a69pxsrzre8re04vh8quuujc8dz2gmc596l2mlj5cpuqp4qwln
                    rune_id: '840106:129'
                    total_balance: '10000000000000'
                    rune_name: SATOSHIRUNETITAN
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Rune name of ID not found
      security:
        - bearerAuth: []
  /btc/{network}/runes/{nameOrId}/addresses/{address}/balances:
    get:
      tags:
        - Runes
      description: Get rune balance by address and rune name or ID.
      operationId: Get Address Runes Balance
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: nameOrId
          in: path
          description: Rune name or ID
          required: true
          schema:
            type: string
        - name: address
          in: path
          description: BTC address
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: paging limit
          required: false
          schema:
            type: number
        - name: offset
          in: query
          description: paging offset
          required: false
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    rune_id: '1:0'
                    rune_name: UNCOMMONGOODS
                    total_balance: '1005'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Rune name of ID not found
      security:
        - bearerAuth: []
  /btc/{network}/runes/{nameOrId}/addresses/{address}/utxos:
    get:
      tags:
        - Runes
      description: Get rune UTXO by address and rune name or ID.
      operationId: Get Address Runes UTXO
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: nameOrId
          in: path
          description: Rune name or ID
          required: true
          schema:
            type: string
        - name: address
          in: path
          description: BTC address
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: paging limit
          required: false
          schema:
            type: number
        - name: offset
          in: query
          description: paging offset
          required: false
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    outpoint: 914909980a0abb7271f91c4832dac09547e56afb730a540a48b8d46f814cb134:1
                    rune_id: '1:0'
                    balance: '1'
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    outpoint: a429e7b8f6c3134e657fe63f3bb41a4e0e027f9dcce223fb77a6cfc5dc74a403:1
                    rune_id: '1:0'
                    balance: '1'
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    outpoint: c985116051d0fbad69bc17d63cce178013fb01fc49160fb099fd464ccd2180eb:1
                    rune_id: '1:0'
                    balance: '1'
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    outpoint: 69c52b0c1b766101bb99c7bbaa6e9a055ac11d72eb4cf619c17c0313cd478064:1
                    rune_id: '1:0'
                    balance: '1'
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    outpoint: 2b44144c449052bd1ee0428aab6563fde8b35859a7b1a461accf0c9ffebe1886:1
                    rune_id: '1:0'
                    balance: '1'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Rune name of ID not found
      security:
        - bearerAuth: []
  /btc/{network}/runes/addresses/{address}/balances:
    get:
      tags:
        - Runes
      description: Get runes balance list by address
      operationId: Get Address Runes Balance List
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: address
          in: path
          description: BTC address
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: paging limit
          required: false
          schema:
            type: number
        - name: offset
          in: query
          description: paging offset
          required: false
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    rune_id: '842029:1175'
                    rune_name: WHERELAMBOGORILLA
                    total_balance: '2000000'
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    rune_id: '1:0'
                    rune_name: UNCOMMONGOODS
                    total_balance: '1005'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Rune name of ID not found
      security:
        - bearerAuth: []
  /btc/{network}/runes/addresses/{address}/utxos:
    get:
      tags:
        - Runes
      description: Get runes UTXO list by address
      operationId: Get Address Runes UTXO List
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: address
          in: path
          description: BTC address
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: paging limit
          required: false
          schema:
            type: number
        - name: offset
          in: query
          description: paging offset
          required: false
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    outpoint: 914909980a0abb7271f91c4832dac09547e56afb730a540a48b8d46f814cb134:1
                    rune_id: '1:0'
                    balance: '1'
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    outpoint: a429e7b8f6c3134e657fe63f3bb41a4e0e027f9dcce223fb77a6cfc5dc74a403:1
                    rune_id: '1:0'
                    balance: '1'
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    outpoint: c985116051d0fbad69bc17d63cce178013fb01fc49160fb099fd464ccd2180eb:1
                    rune_id: '1:0'
                    balance: '1'
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    outpoint: 69c52b0c1b766101bb99c7bbaa6e9a055ac11d72eb4cf619c17c0313cd478064:1
                    rune_id: '1:0'
                    balance: '1'
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    outpoint: 2b44144c449052bd1ee0428aab6563fde8b35859a7b1a461accf0c9ffebe1886:1
                    rune_id: '1:0'
                    balance: '1'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Rune name of ID not found
      security:
        - bearerAuth: []
  /btc/{network}/runes/outpoints/{outpoint}/balances:
    get:
      tags:
        - Runes
      description: Get runes balance list by transaction outpoint.
      operationId: Get Outpoint Runes Balance List
      parameters:
        - name: network
          in: path
          description: BTC chain network (mainnet | testnet | signet)
          required: true
          schema:
            type: string
        - name: outpoint
          in: path
          description: BTC transaction outpint in format `txid:vout`
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                statusCode: 0
                data:
                  - pkscript: 5120a3f9284e20f373aa97d961238d44db854d4616f430aec037893dc4de4c7c3852
                    wallet_addr: bc1p50ujsn3q7de6497evy3c63xms4x5v9h5xzhvqduf8hzdunru8pfqdkgw29
                    rune_id: '1:0'
                    balance: '1'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Rune name of ID not found
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
